import { PropertyItem, PropertyFilter } from '@/types/proptis'

export const INITIAL_PROPERTIES: PropertyItem[] = [
  {
    id: 'prop-1',
    ownerId: 'cortex-admin-1',
    title: 'The Sky Villa at Sapphire Heights',
    slug: 'sky-villa-sapphire-heights',
    category: 'Luxury Villas',
    purpose: 'For Sale',
    price: 45000000,
    currency: '₹',
    pricePerSqFt: 9000,
    areaSqFt: 5000,
    bedrooms: 5,
    bathrooms: 6,
    balcony: 3,
    kitchen: 2,
    parking: 4,
    facing: 'North-East',
    floor: 24,
    totalFloors: 25,
    propertyAgeYears: 1,
    furnishing: 'Furnished',
    description:
      'An architectural masterpiece with panoramic city views, private infinity pool, Italian marble flooring, double-height ceilings, and full smart home automation powered by Cortex IoT.',
    location: {
      country: 'India',
      state: 'Punjab',
      district: 'Jalandhar',
      city: 'Jalandhar',
      area: 'Model Town',
      locality: 'Sapphire Boulevard',
      pincode: '144003',
      landmark: 'Near Model Town Club',
      street: 'Royal Avenue',
      houseNumber: 'Penthouse A-24',
      latitude: 31.326,
      longitude: 75.576,
    },
    amenities: [
      'Swimming Pool',
      'Lift',
      'Garden',
      'Gym',
      'Power Backup',
      'Solar',
      'Water Supply',
      'Internet',
      'Club House',
      'Security',
      'CCTV',
      'EV Charging',
      'Fire Safety',
      'Rain Water Harvesting',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop',
    ],
    coverImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
    virtualTour360Url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    floorPlanUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1200&auto=format&fit=crop',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    metaTitle: 'The Sky Villa - Luxury Property in Jalandhar | Proptis',
    metaDescription: 'Explore 5 BHK luxury penthouse in Model Town Jalandhar. Private infinity pool, smart automation, 5000 sq ft.',
    keywords: ['luxury villa', 'jalandhar real estate', 'penthouse for sale', 'model town villa'],
    status: 'Published',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-28T14:30:00Z',
    isFeatured: true,
    isVerified: true,
    analytics: {
      views: 1240,
      dailyViews: [42, 58, 65, 80, 72, 94, 110],
      monthlyViews: [310, 450, 480, 1240],
      whatsappClicks: 184,
      callClicks: 96,
      emailClicks: 32,
    },
    owner: {
      id: 'cortex-admin-1',
      name: 'Gurvinder Singh (Cortex Realty)',
      email: 'gurvinder@cortexsolutions.com',
      phone: '+91 63769 30459',
      whatsapp: '916376930459',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
      agency: 'Cortex Luxury Realty',
      isVerified: true,
    },
  },
  {
    id: 'prop-2',
    ownerId: 'cortex-admin-1',
    title: 'Royal Palm Estate & Golf Residence',
    slug: 'royal-palm-estate-golf-residence',
    category: 'Farm Houses',
    purpose: 'For Sale',
    price: 82000000,
    currency: '₹',
    pricePerSqFt: 6833,
    areaSqFt: 12000,
    bedrooms: 6,
    bathrooms: 7,
    balcony: 4,
    kitchen: 2,
    parking: 8,
    facing: 'East',
    floor: 2,
    totalFloors: 2,
    propertyAgeYears: 0,
    furnishing: 'Furnished',
    description:
      'Sprawling ultra-luxury estate featuring a private organic orchard, mini golf course, 6-car garage, temperature-controlled swimming pool, and guest cottage.',
    location: {
      country: 'India',
      state: 'Punjab',
      district: 'Jalandhar',
      city: 'Jalandhar',
      area: 'Cantonment',
      locality: 'Palm Drive',
      pincode: '144005',
      landmark: 'Near Cantt Railway Station',
      latitude: 31.300,
      longitude: 75.590,
    },
    amenities: [
      'Swimming Pool',
      'Garden',
      'Gym',
      'Power Backup',
      'Solar',
      'Internet',
      'Club House',
      'Kids Area',
      'Temple',
      'Security',
      'CCTV',
      'EV Charging',
    ],
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?q=80&w=1200&auto=format&fit=crop',
    ],
    coverImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop',
    metaTitle: 'Royal Palm Estate | 12,000 Sq Ft Farm House in Jalandhar',
    metaDescription: 'Buy luxury farmhouse with mini golf, orchard, private pool in Cantt Jalandhar.',
    keywords: ['farmhouse for sale', 'jalandhar estate', 'luxury farm house'],
    status: 'Published',
    createdAt: '2026-07-05T09:00:00Z',
    updatedAt: '2026-07-25T11:20:00Z',
    isFeatured: true,
    isVerified: true,
    analytics: {
      views: 890,
      dailyViews: [30, 45, 52, 60, 85, 90, 102],
      monthlyViews: [200, 310, 380, 890],
      whatsappClicks: 142,
      callClicks: 64,
      emailClicks: 21,
    },
    owner: {
      id: 'cortex-admin-1',
      name: 'Anmol Singh (Cortex Realty)',
      email: 'anmol@cortexsolutions.com',
      phone: '+91 63769 30459',
      whatsapp: '916376930459',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
      agency: 'Cortex Commercial & Luxury',
      isVerified: true,
    },
  },
  {
    id: 'prop-3',
    ownerId: 'cortex-admin-2',
    title: 'Cortex Business Tower & Tech Hub',
    slug: 'cortex-business-tower-tech-hub',
    category: 'Commercial Buildings',
    purpose: 'Commercial',
    price: 120000000,
    currency: '₹',
    pricePerSqFt: 8000,
    areaSqFt: 15000,
    bedrooms: 0,
    bathrooms: 12,
    balcony: 2,
    kitchen: 4,
    parking: 20,
    facing: 'North',
    floor: 8,
    totalFloors: 10,
    propertyAgeYears: 2,
    furnishing: 'Furnished',
    description:
      'Grade A IT park & commercial tower with central HVAC, high-speed elevators, 100% power backup, fiber optic connectivity, conference centers, and cafeteria floor.',
    location: {
      country: 'India',
      state: 'Punjab',
      district: 'Jalandhar',
      city: 'Jalandhar',
      area: 'BMC Chowk',
      locality: 'Tech Hub Boulevard',
      pincode: '144001',
      latitude: 31.320,
      longitude: 75.580,
    },
    amenities: [
      'Lift',
      'Power Backup',
      'Solar',
      'Water Supply',
      'Internet',
      'Metro Nearby',
      'Security',
      'CCTV',
      'Fire Safety',
      'EV Charging',
    ],
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
    ],
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    metaTitle: 'Cortex Business Tower - Commercial Office Space for Sale',
    metaDescription: '15,000 sq ft Grade A commercial tech space at BMC Chowk Jalandhar.',
    keywords: ['commercial building', 'office space jalandhar', 'it park building'],
    status: 'Published',
    createdAt: '2026-07-10T12:00:00Z',
    updatedAt: '2026-07-26T16:45:00Z',
    isFeatured: true,
    isVerified: true,
    analytics: {
      views: 1560,
      dailyViews: [60, 75, 90, 110, 140, 160, 180],
      monthlyViews: [400, 600, 800, 1560],
      whatsappClicks: 210,
      callClicks: 115,
      emailClicks: 48,
    },
    owner: {
      id: 'cortex-admin-2',
      name: 'Cortex Corporate Sales',
      email: 'sales@cortexsolutions.com',
      phone: '+91 63769 30459',
      whatsapp: '916376930459',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=300&auto=format&fit=crop',
      agency: 'Cortex Enterprise Real Estate',
      isVerified: true,
    },
  },
  {
    id: 'prop-4',
    ownerId: 'cortex-admin-1',
    title: 'Emerald Bay Luxury Apartment',
    slug: 'emerald-bay-luxury-apartment',
    category: 'Apartments',
    purpose: 'For Rent',
    price: 75000,
    currency: '₹',
    pricePerSqFt: 35,
    areaSqFt: 2200,
    bedrooms: 3,
    bathrooms: 3,
    balcony: 2,
    kitchen: 1,
    parking: 2,
    facing: 'South-East',
    floor: 12,
    totalFloors: 18,
    propertyAgeYears: 1,
    furnishing: 'Furnished',
    description:
      'Fully furnished 3 BHK sea-view style luxury apartment with modular kitchen, smart lighting, 24/7 security concierge, and clubhouse access.',
    location: {
      country: 'India',
      state: 'Punjab',
      district: 'Jalandhar',
      city: 'Jalandhar',
      area: 'Urban Estate Phase 2',
      locality: 'Emerald Greens',
      pincode: '144022',
      latitude: 31.295,
      longitude: 75.610,
    },
    amenities: [
      'Swimming Pool',
      'Lift',
      'Gym',
      'Power Backup',
      'Internet',
      'Club House',
      'Security',
      'CCTV',
    ],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    coverImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
    metaTitle: 'Emerald Bay 3BHK Rental Apartment in Urban Estate Jalandhar',
    metaDescription: 'Rent 3BHK luxury furnished apartment in Urban Estate Phase 2 Jalandhar.',
    keywords: ['flat for rent', '3bhk apartment', 'urban estate rent'],
    status: 'Published',
    createdAt: '2026-07-15T08:30:00Z',
    updatedAt: '2026-07-27T09:15:00Z',
    isFeatured: false,
    isVerified: true,
    analytics: {
      views: 640,
      dailyViews: [20, 30, 45, 50, 70, 85, 95],
      monthlyViews: [150, 240, 320, 640],
      whatsappClicks: 92,
      callClicks: 41,
      emailClicks: 12,
    },
    owner: {
      id: 'cortex-admin-1',
      name: 'Gurvinder Singh (Cortex Realty)',
      email: 'gurvinder@cortexsolutions.com',
      phone: '+91 63769 30459',
      whatsapp: '916376930459',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
      agency: 'Cortex Luxury Realty',
      isVerified: true,
    },
  },
]

export const ALL_AMENITIES = [
  'Swimming Pool', 'Lift', 'Garden', 'Gym', 'Power Backup', 'Solar',
  'Water Supply', 'Internet', 'Club House', 'Kids Area', 'Temple',
  'Hospital Nearby', 'School Nearby', 'Market Nearby', 'Metro Nearby',
  'Security', 'CCTV', 'Fire Safety', 'Rain Water Harvesting', 'EV Charging',
  'Intercom', 'Jacuzzi', 'Sauna', 'Tennis Court', 'Squash Court', 'Golf Course',
  'Helipad', 'Private Pool', 'Servant Quarter', 'Private Terrace', 'Modular Kitchen',
  'Central AC', 'Smart Home Automation', 'Car Parking', 'Visitor Parking', 'Jogging Track',
  'Barbecue Area', 'Spa', 'Concierge Service', 'Maintenance Staff', 'Waste Disposal',
  'Pet Friendly', 'Laundry Service', 'Vastu Compliant', 'Library', 'Mini Theatre',
]
