'use client';
import React from 'react';
import { FileText, ShieldCheck, Scale, AlertCircle } from 'lucide-react';

const TermsAndConditions = () => {
  const lastUpdated = "December 24, 2025";

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 py-40 px-4 sm:px-6 lg:px-8 transition-colors duration-300">
      <div className="max-w-4xl mx-auto">
        
        {/* Header Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white mb-4 tracking-tight">
            Terms & Conditions
          </h1>
          <p className="text-gray-600 dark:text-gray-400 font-medium">Last Updated: {lastUpdated}</p>
          <div className="mt-4 flex justify-center">
            <div className="h-1.5 w-20 bg-blue-600 rounded-full"></div>
          </div>
        </div>

        {/* Legal Notice Box - Dark Mode Optimized */}
        <div className="bg-blue-50 dark:bg-blue-900/20 border-l-4 border-blue-600 p-6 mb-10 rounded-r-lg shadow-sm">
          <div className="flex">
            <div className="flex-shrink-0">
              <AlertCircle className="h-6 w-6 text-blue-600 dark:text-blue-400" />
            </div>
            <div className="ml-3">
              <p className="text-sm text-blue-800 dark:text-blue-200 leading-relaxed">
                This document is an electronic record in terms of Information Technology Act, 2000... 
                (Generated by a computer system and does not require signatures).
              </p>
            </div>
          </div>
        </div>

        {/* Main Content Card */}
        <div className="bg-white dark:bg-gray-900 shadow-xl border border-gray-200 dark:border-gray-800 rounded-2xl overflow-hidden transition-all">
          <div className="p-6 md:p-10 space-y-12">
            
            {/* Section 1: Introduction */}
            <section>
              <div className="flex items-center mb-5">
                <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg mr-3">
                  <FileText className="h-6 w-6 text-blue-600 dark:text-blue-400" />
                </div>
                <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">1. Introduction</h2>
              </div>
              <div className="text-gray-600 dark:text-gray-300 leading-relaxed space-y-4 text-md">
                <p>
                  This document is published for access or usage of domain name 
                  <span className="font-semibold text-blue-600 dark:text-blue-400 underline ml-1">https://cortestack.com</span>.
                </p>
                <p>
                  The Platform is owned by <span className="font-bold text-gray-900 dark:text-white">8094997023</span>, 
                  registered office at <span className="italic">gjsinghpur padampur road near the caffe house</span>.
                </p>
              </div>
            </section>

            {/* Section 2: User Obligations */}
            <section>
              <div className="flex items-center mb-5">
                <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg mr-3">
                  <ShieldCheck className="h-6 w-6 text-blue-600 dark:text-blue-400" />
                </div>
                <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-100">2. Terms of Use</h2>
              </div>
              <ul className="grid grid-cols-1 gap-4 text-gray-600 dark:text-gray-300">
                {[
                  "Provide true, accurate and complete information during registration.",
                  "Use of Services is solely and entirely at your own risk.",
                  "Contents are proprietary; no intellectual property rights granted.",
                  "Unauthorized use may lead to legal action under Indian law.",
                  "Agreement to pay charges associated with availing the Services."
                ].map((item, index) => (
                  <li key={index} className="flex items-start">
                    <span className="h-2 w-2 mt-2 mr-3 bg-blue-500 rounded-full flex-shrink-0"></span>
                    {item}
                  </li>
                ))}
              </ul>
            </section>

            {/* Section 3: Liability */}
            <section className="bg-gray-50 dark:bg-gray-800/50 p-6 rounded-xl border border-gray-100 dark:border-gray-700">
              <div className="flex items-center mb-4">
                <Scale className="h-6 w-6 text-blue-600 dark:text-blue-400 mr-2" />
                <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100">3. Liability & Warranty</h2>
              </div>
              <p className="text-gray-600 dark:text-gray-400 italic text-sm leading-loose">
                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, 
                timeliness, or suitability of the information offered for any specific purpose. 
                We expressly exclude liability for inaccuracies to the fullest extent permitted by law.
              </p>
            </section>

            {/* Section 4: Jurisdiction */}
            <section className="bg-gradient-to-br from-gray-900 to-black text-white p-8 rounded-2xl shadow-inner">
              <h2 className="text-xl font-bold mb-4 text-blue-400">4. Governing Law</h2>
              <p className="text-gray-300 mb-6">
                These Terms shall be governed by the laws of India. All disputes are subject to the 
                exclusive jurisdiction of the courts in <span className="text-white font-semibold">Padampur/Rajasthan</span>.
              </p>
              <div className="text-sm text-gray-400 border-t border-gray-800 pt-4">
                Questions? Email us at your-email@cortestack.com
              </div>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;