import React from 'react';
import { FileText, ShieldCheck, Scale, AlertCircle } from 'lucide-react';

const TermsAndConditions = () => {
  const lastUpdated = "December 24, 2025";

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-extrabold text-gray-900 mb-4 tracking-tight">
            Terms & Conditions
          </h1>
          <p className="text-gray-600">Last Updated: {lastUpdated}</p>
          <div className="mt-4 flex justify-center">
            <div className="h-1 w-20 bg-blue-600 rounded"></div>
          </div>
        </div>

        {/* Legal Notice Box */}
        <div className="bg-blue-50 border-l-4 border-blue-600 p-6 mb-10 rounded-r-lg">
          <div className="flex">
            <div className="flex-shrink-0">
              <AlertCircle className="h-6 w-6 text-blue-600" />
            </div>
            <div className="ml-3">
              <p className="text-sm text-blue-800 leading-relaxed">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="bg-white shadow-sm border border-gray-200 rounded-2xl overflow-hidden">
          <div className="p-8 space-y-10">
            
            {/* Section 1: Introduction */}
            <section>
              <div className="flex items-center mb-4">
                <FileText className="h-6 w-6 text-blue-600 mr-2" />
                <h2 className="text-2xl font-bold text-gray-800">1. Introduction</h2>
              </div>
              <div className="text-gray-600 leading-relaxed space-y-4">
                <p>
                  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 for access or usage of domain name <span className="font-semibold text-blue-600 underline">https://cortestack.com</span> (&apos;Website&apos;).
                </p>
                <p>
                  The Platform is owned by <span className="font-bold text-gray-800">8094997023</span>, a company incorporated under the Companies Act, 1956 with its registered office at <span className="italic text-gray-700">gjsinghpur padampur road near the caffe house</span> (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
                </p>
              </div>
            </section>

            <hr className="border-gray-100" />

            {/* Section 2: User Obligations */}
            <section>
              <div className="flex items-center mb-4">
                <ShieldCheck className="h-6 w-6 text-blue-600 mr-2" />
                <h2 className="text-2xl font-bold text-gray-800">2. Terms of Use</h2>
              </div>
              <ul className="list-disc pl-5 space-y-3 text-gray-600">
                <li>You agree to provide true, accurate and complete information during and after registration.</li>
                <li>Your use of our Services and the Platform is solely at your own risk.</li>
                <li>The contents of the Platform (design, layout, graphics) are proprietary to us.</li>
                <li>Unauthorized use of this Platform may lead to legal action.</li>
                <li>You agree not to use the Platform for any purpose that is unlawful or illegal.</li>
              </ul>
            </section>

            <hr className="border-gray-100" />

            {/* Section 3: Liability & Warranty */}
            <section>
              <div className="flex items-center mb-4">
                <Scale className="h-6 w-6 text-blue-600 mr-2" />
                <h2 className="text-2xl font-bold text-gray-800">3. Liability & Warranty</h2>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                <p className="text-gray-600 italic">
                  &quot;Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website.&quot;
                </p>
              </div>
            </section>

            <hr className="border-gray-100" />

            {/* Section 4: Governing Law */}
            <section className="bg-gray-900 text-white p-8 rounded-xl">
              <h2 className="text-xl font-bold mb-4">4. Governing Law & Jurisdiction</h2>
              <p className="text-gray-300 leading-relaxed mb-4">
                These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India.
              </p>
              <p className="text-gray-300">
                All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <span className="text-blue-400 font-medium">[Insert City/State]</span>.
              </p>
            </section>

          </div>
        </div>

        {/* Footer Contact */}
        <div className="mt-10 text-center">
          <p className="text-gray-500 text-sm">
            Have questions? Contact us through the information provided on our homepage.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;